# Generated by Django 5.1.3 on 2026-06-20 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_PRESSURE', 'Presión Baja'), ('HIGH_PRESSURE', 'Presión Alta'), ('HIGH_TEMPERATURE', 'Temperatura Alta'), ('PUNCTURE', 'Pinchazo'), ('TIRE_WEAR_WARNING', 'Advertencia Desgaste'), ('TIRE_WEAR_CRITICAL', 'Desgaste Crítico'), ('SENSOR_OFFLINE', 'Sensor Desconectado'), ('LOW_BATTERY_SENSOR', 'Batería Baja (Sensor)'), ('LOW_BATTERY_MASTER', 'Batería Baja (Maestro)'), ('HARD_BRAKING', 'Frenazo Brusco'), ('HARD_ACCELERATION', 'Aceleración Brusca'), ('HOS_WARNING', 'Advertencia HOS'), ('HOS_VIOLATION', 'Violación HOS'), ('OVERWEIGHT_AXLE', 'Exceso Peso Eje'), ('OVERWEIGHT_GROSS', 'Exceso Peso Bruto')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('trigger_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('ACKNOWLEDGED', 'Reconocida'), ('RESOLVED', 'Resuelta')], default='ACTIVE', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.tiresensor')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_alerts', to='devices.truck')),
            ],
        ),
    ]
