# Generated by Django 5.1.3 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SizeWeightRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, unique=True)),
                ('max_weight_lbs', models.FloatField(default=80000.0)),
                ('max_length_ft', models.FloatField(default=65.0)),
                ('max_width_in', models.FloatField(default=102.0)),
                ('max_height_ft', models.FloatField(default=13.5)),
            ],
        ),
        migrations.CreateModel(
            name='WIMStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('station_code', models.CharField(max_length=50, unique=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
