# Generated by Django 5.1.3 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_number', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('dba_name', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('num_power_units', models.IntegerField(default=0)),
                ('num_drivers', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTransportIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('indicator_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
