# Generated by Django 5.1.3 on 2026-06-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título Descriptivo')),
                ('dataset_type', models.CharField(choices=[('TRUCK_STOPS', 'Truck Stops (NTAD)'), ('WIM_STATIONS', 'WIM Stations (NTAD)'), ('TIRE_SHOPS', 'Tire Shops (OSM)'), ('ALT_FUEL', 'Alternative Fuel Stations'), ('CARRIERS', 'Carrier Companies (FMCSA)'), ('ROUTES_NHS', 'National Highway System (GeoJSON)'), ('OTHER', 'Otro / Sin clasificar')], max_length=50, verbose_name='Tipo de Dataset')),
                ('file', models.FileField(upload_to='datasets/%Y/%m/', verbose_name='Archivo Original (CSV/Excel/GeoJSON)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Procesamiento'), ('PROCESSING', 'Procesando...'), ('COMPLETED', 'Completado con Éxito'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado ETL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('processing_logs', models.TextField(blank=True, null=True, verbose_name='Logs de Procesamiento')),
            ],
            options={
                'verbose_name': 'Subida de Dataset',
                'verbose_name_plural': 'Subidas de Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
