# Generated by Django 5.1.3 on 2026-06-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_alter_datasetupload_dataset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Dataset')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo (Local o S3)')),
                ('file_type', models.CharField(choices=[('CSV', 'CSV'), ('GEOJSON', 'GeoJSON'), ('EXCEL', 'Excel')], default='CSV', max_length=50)),
                ('schema', models.JSONField(blank=True, null=True, verbose_name='Esquema/Estructura Esperada')),
                ('last_load', models.DateTimeField(blank=True, null=True, verbose_name='Última Carga Exitosa')),
            ],
            options={
                'verbose_name': 'Fuente de Datos',
                'verbose_name_plural': 'Fuentes de Datos',
            },
        ),
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En Ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='data_ingestion.datasource')),
            ],
            options={
                'verbose_name': 'Trabajo ETL',
                'verbose_name_plural': 'Trabajos ETL',
                'ordering': ['-started_at'],
            },
        ),
        migrations.DeleteModel(
            name='DatasetUpload',
        ),
    ]
