"""Constantes regulatorias FMCSA para Hours of Service."""

MAX_DRIVING_HOURS = 11
MAX_ON_DUTY_HOURS = 14
BREAK_REQUIRED_AFTER = 8
BREAK_MINUTES = 30
MIN_OFF_DUTY_HOURS = 10
SLEEPER_SPLIT_PRIMARY_HOURS = 7
SLEEPER_SPLIT_SECONDARY_HOURS = 2
ADVERSE_CONDITIONS_EXT = 2
SHORT_HAUL_RADIUS_MILES = 150
SHORT_HAUL_MAX_HOURS = 14
CYCLE_60_HOURS_LIMIT = 60
CYCLE_70_HOURS_LIMIT = 70
WARNING_THRESHOLD_MINUTES = 60
