# Generated by Django 5.1.3 on 2026-06-19 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Licencia (CDL)')),
                ('license_state', models.CharField(max_length=2, verbose_name='Estado Emisor')),
                ('cdl_class', models.CharField(default='A', max_length=1, verbose_name='Clase CDL')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('SUSPENDED', 'Suspendido')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Marca de Tiempo')),
                ('status', models.CharField(choices=[('DRIVING', 'Driving'), ('ON_DUTY', 'On-Duty (Not Driving)'), ('OFF_DUTY', 'Off-Duty'), ('SLEEPER', 'Sleeper Berth')], max_length=20, verbose_name='Estado de Servicio')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación Registrada')),
                ('odometer', models.FloatField(verbose_name='Odómetro (Millas)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hos_monitoring.driver')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.truck')),
            ],
            options={
                'verbose_name': 'Registro de Conductor (ELD)',
                'verbose_name_plural': 'Registros de Conductores (ELD)',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VIOLATION_11H', 'Violación: Límite de 11h de Conducción'), ('VIOLATION_14H', 'Violación: Límite de 14h On-Duty'), ('VIOLATION_30M', 'Violación: Falta de Pausa de 30 minutos'), ('VIOLATION_60_70H', 'Violación: Límite de Ciclo 60/70 horas'), ('WARNING_11H', 'Advertencia: Cerca del Límite de 11h'), ('WARNING_14H', 'Advertencia: Cerca del Límite de 14h'), ('WARNING_30M', 'Advertencia: Pausa de 30 min inminente'), ('WARNING_60_70H', 'Advertencia: Cerca del Límite de Ciclo')], max_length=20, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('WARNING', 'Advertencia'), ('VIOLATION', 'Violación Crítica')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Valor Actual (Horas)')),
                ('threshold_value', models.FloatField(blank=True, null=True, verbose_name='Límite Permitido (Horas)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('ACKNOWLEDGED', 'Reconocida'), ('RESOLVED', 'Resuelta')], default='ACTIVE', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hos_alerts', to='hos_monitoring.driver')),
            ],
            options={
                'verbose_name': 'Alerta HOS',
                'verbose_name_plural': 'Alertas HOS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HOSCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start', models.DateTimeField(verbose_name='Inicio del Ciclo de 7/8 días')),
                ('cycle_type', models.CharField(choices=[('60_7', '60 horas en 7 días'), ('70_8', '70 horas en 8 días')], default='70_8', max_length=20)),
                ('driving_time_today', models.IntegerField(default=0, verbose_name='Tiempo de Conducción Hoy (min)')),
                ('on_duty_time_today', models.IntegerField(default=0, verbose_name='Tiempo On-Duty Hoy (min)')),
                ('consecutive_driving_time', models.IntegerField(default=0, verbose_name='Tiempo de Conducción Consecutiva (min)')),
                ('hours_7days', models.IntegerField(default=0, verbose_name='Horas On-Duty 7 Días (min)')),
                ('hours_8days', models.IntegerField(default=0, verbose_name='Horas On-Duty 8 Días (min)')),
                ('last_10h_off', models.DateTimeField(blank=True, null=True, verbose_name='Último Descanso 10h')),
                ('last_30min_break', models.DateTimeField(blank=True, null=True, verbose_name='Último Descanso 30min')),
                ('is_short_haul', models.BooleanField(default=False, verbose_name='Excepción Short-Haul (150 millas)')),
                ('adverse_conditions', models.BooleanField(default=False, verbose_name='Condiciones Adversas (+2h)')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='En Cumplimiento')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hos_compliance', to='hos_monitoring.driver')),
            ],
            options={
                'verbose_name': 'Cumplimiento HOS',
                'verbose_name_plural': 'Cumplimientos HOS',
            },
        ),
    ]
