# Generated by Django 5.1.3 on 2026-06-19 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_weightenforcementstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='VIN')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('num_tires', models.IntegerField(default=18, verbose_name='Número de Llantas')),
                ('status', models.CharField(default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='core.carriercompany')),
            ],
            options={
                'verbose_name': 'Tractomula',
                'verbose_name_plural': 'Tractomulas',
            },
        ),
        migrations.CreateModel(
            name='MasterDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=50, unique=True, verbose_name='Código del Dispositivo')),
                ('firmware_version', models.CharField(max_length=20, verbose_name='Versión Firmware')),
                ('sim_card', models.CharField(max_length=30, verbose_name='SIM Card (ICCID)')),
                ('battery_level', models.FloatField(default=100.0, verbose_name='Nivel de Batería (%)')),
                ('signal_strength', models.FloatField(default=0.0, verbose_name='Señal (dBm)')),
                ('status', models.CharField(default='ONLINE', max_length=20, verbose_name='Estado')),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_device', to='devices.truck', verbose_name='Tractomula Asignada')),
            ],
            options={
                'verbose_name': 'Dispositivo Maestro',
                'verbose_name_plural': 'Dispositivos Maestros',
            },
        ),
        migrations.CreateModel(
            name='VehicleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Marca de Tiempo')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed_mph', models.FloatField(verbose_name='Velocidad (mph)')),
                ('heading', models.FloatField(verbose_name='Rumbo (grados)')),
                ('obd_rpm', models.FloatField(blank=True, null=True, verbose_name='RPM')),
                ('obd_fuel_level', models.FloatField(blank=True, null=True, verbose_name='Nivel Combustible (%)')),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True, verbose_name='Voltaje Batería (V)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_readings', to='devices.masterdevice')),
            ],
            options={
                'verbose_name': 'Lectura de Vehículo',
                'verbose_name_plural': 'Lecturas de Vehículos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TireSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_code', models.CharField(max_length=50, unique=True, verbose_name='Código del Sensor')),
                ('position', models.CharField(choices=[('FL-1', 'FL-1'), ('FL-2', 'FL-2'), ('FL-3', 'FL-3'), ('FL-4', 'FL-4'), ('FR-1', 'FR-1'), ('FR-2', 'FR-2'), ('FR-3', 'FR-3'), ('FR-4', 'FR-4'), ('RL-1', 'RL-1'), ('RL-2', 'RL-2'), ('RL-3', 'RL-3'), ('RL-4', 'RL-4'), ('RR-1', 'RR-1'), ('RR-2', 'RR-2'), ('RR-3', 'RR-3'), ('RR-4', 'RR-4'), ('TL-1', 'TL-1'), ('TL-2', 'TL-2'), ('TL-3', 'TL-3'), ('TL-4', 'TL-4'), ('TR-1', 'TR-1'), ('TR-2', 'TR-2'), ('TR-3', 'TR-3'), ('TR-4', 'TR-4')], max_length=10, verbose_name='Posición (Eje)')),
                ('tire_brand', models.CharField(max_length=50, verbose_name='Marca de Llanta')),
                ('install_date', models.DateField(verbose_name='Fecha de Instalación')),
                ('lifecycle_km', models.FloatField(default=200000.0, verbose_name='Ciclo de Vida Estimado (km/millas)')),
                ('accumulated_km', models.FloatField(default=0.0, verbose_name='Recorrido Acumulado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_sensors', to='devices.masterdevice', verbose_name='Dispositivo Maestro')),
            ],
            options={
                'verbose_name': 'Sensor de Llanta',
                'verbose_name_plural': 'Sensores de Llantas',
                'unique_together': {('master_device', 'position')},
            },
        ),
    ]
