# Generated by Django 5.1.3 on 2026-06-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Amenidad')),
                ('category', models.CharField(blank=True, help_text='Ej: Alimentación, Mantenimiento, Descanso', max_length=100, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Amenity / Service',
                'verbose_name_plural': 'Amenities / Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarrierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_number', models.CharField(max_length=50, unique=True, verbose_name='DOT Number')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Legal Name')),
                ('dba_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='DBA Name')),
                ('carrier_operation', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlternativeFuelStation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.location')),
                ('fuel_type_code', models.CharField(max_length=20)),
                ('station_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('ev_connector_types', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Alternative Fuel Station',
                'verbose_name_plural': 'Alternative Fuel Stations',
            },
            bases=('core.location',),
        ),
        migrations.CreateModel(
            name='TireShop',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.location')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('is_24_hours', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tire Shop',
                'verbose_name_plural': 'Tire Shops',
            },
            bases=('core.location',),
        ),
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.location')),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_spaces', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Truck Stop',
                'verbose_name_plural': 'Truck Stops',
            },
            bases=('core.location',),
        ),
        migrations.CreateModel(
            name='WIMStation',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.location')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('direction_of_travel', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_lanes', models.IntegerField(default=1)),
                ('status', models.CharField(default='Operational', max_length=50)),
            ],
            options={
                'verbose_name': 'WIM Station',
                'verbose_name_plural': 'WIM Stations',
            },
            bases=('core.location',),
        ),
        migrations.AddField(
            model_name='location',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='locations', to='core.amenity', verbose_name='Servicios y Amenidades'),
        ),
    ]
