# Generated by Django 5.1.3 on 2026-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativefuelstation',
            name='station_phone',
        ),
        migrations.RemoveField(
            model_name='tireshop',
            name='phone',
        ),
        migrations.AddField(
            model_name='location',
            name='operator',
            field=models.CharField(default='Sin Información', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(default='Sin Información', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
