# Generated by Django 5.1.3 on 2026-06-18 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_alternativefuelstation_station_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingFacility',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.location')),
                ('population_served', models.IntegerField(blank=True, default=0, null=True)),
                ('tires_recycled_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tires_generated_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Recycling Facility',
                'verbose_name_plural': 'Recycling Facilities',
            },
            bases=('core.location',),
        ),
        migrations.CreateModel(
            name='TransportationStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('highway_fatalities', models.IntegerField(blank=True, null=True)),
                ('truck_employment', models.IntegerField(blank=True, null=True)),
                ('truck_tonnage_index', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diesel_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transportation Statistic',
                'verbose_name_plural': 'Transportation Statistics',
                'ordering': ['-date'],
            },
        ),
    ]
