# Generated by Django 5.1.3 on 2026-06-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recyclingfacility_transportationstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativefuelstation',
            name='cng_dispenser_num',
            field=models.IntegerField(default=0, verbose_name='Número de Islas CNG'),
        ),
        migrations.AddField(
            model_name='alternativefuelstation',
            name='ev_dc_fast_count',
            field=models.IntegerField(default=0, verbose_name='Número de Islas EV Rápidas'),
        ),
        migrations.AddField(
            model_name='alternativefuelstation',
            name='maximum_vehicle_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clase Máxima de Vehículo'),
        ),
        migrations.AddField(
            model_name='truckstop',
            name='diesel_lanes',
            field=models.IntegerField(default=0, verbose_name='Islas Diésel Tractomulas'),
        ),
    ]
