# Generated by Django 5.1.3 on 2026-06-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alternativefuelstation_cng_dispenser_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightEnforcementStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('state', models.CharField(max_length=10, verbose_name='Estado')),
                ('vehicles_weighed_fixed', models.BigIntegerField(default=0, verbose_name='Pesados (Báscula Fija)')),
                ('vehicles_weighed_wim', models.BigIntegerField(default=0, verbose_name='Pesados (WIM en movimiento)')),
                ('oversize_violations', models.IntegerField(default=0, verbose_name='Multas por Tamaño')),
                ('overweight_violations', models.IntegerField(default=0, verbose_name='Multas por Peso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Weight Enforcement Stat',
                'verbose_name_plural': 'Weight Enforcement Stats',
                'ordering': ['-year', 'state'],
                'unique_together': {('year', 'state')},
            },
        ),
    ]
