# Generated by Django 5.1.3 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighwayRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=100, unique=True)),
                ('route_name', models.CharField(max_length=255)),
                ('route_type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('length_km', models.FloatField(default=0.0)),
            ],
        ),
    ]
