# Generated by Django 5.1.3 on 2026-06-23 20:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0004_datasource_etljob_delete_datasetupload'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highwayroute',
            options={'verbose_name': 'Ruta Nacional', 'verbose_name_plural': 'Rutas Nacionales'},
        ),
        migrations.AddField(
            model_name='highwayroute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highwayroute',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HPMSInventorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('state_code', models.CharField(blank=True, max_length=3)),
                ('api_url', models.URLField(max_length=500)),
                ('map_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hpms_sources', to='data_ingestion.datasource')),
            ],
            options={
                'verbose_name': 'Fuente HPMS',
                'verbose_name_plural': 'Fuentes HPMS',
                'ordering': ['state_name'],
            },
        ),
        migrations.CreateModel(
            name='HPMSLayerCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.IntegerField()),
                ('layer_name', models.CharField(max_length=255)),
                ('geometry_type', models.CharField(blank=True, max_length=100)),
                ('supports_query', models.BooleanField(default=False)),
                ('record_count', models.IntegerField(default=0)),
                ('last_schema_sync', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='routes.hpmsinventorysource')),
            ],
            options={
                'verbose_name': 'Capa HPMS',
                'verbose_name_plural': 'Capas HPMS',
                'ordering': ['source__state_name', 'layer_id'],
                'unique_together': {('source', 'layer_id')},
            },
        ),
        migrations.CreateModel(
            name='HPMSRoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_key', models.CharField(max_length=200, unique=True)),
                ('external_segment_id', models.CharField(blank=True, max_length=255)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('county_name', models.CharField(blank=True, max_length=100)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('route_number', models.CharField(blank=True, max_length=100)),
                ('route_type', models.CharField(blank=True, max_length=100)),
                ('functional_class', models.CharField(blank=True, max_length=100)),
                ('is_nhs', models.BooleanField(default=False)),
                ('is_interstate', models.BooleanField(default=False)),
                ('urban_code', models.CharField(blank=True, max_length=100)),
                ('start_measure', models.FloatField(blank=True, null=True)),
                ('end_measure', models.FloatField(blank=True, null=True)),
                ('length_miles', models.FloatField(blank=True, null=True)),
                ('iri', models.FloatField(blank=True, null=True)),
                ('roughness_class', models.CharField(blank=True, max_length=50)),
                ('surface_type', models.CharField(blank=True, max_length=100)),
                ('pavement_type', models.CharField(blank=True, max_length=100)),
                ('aadt', models.IntegerField(blank=True, null=True)),
                ('truck_aadt', models.IntegerField(blank=True, null=True)),
                ('lane_count', models.IntegerField(blank=True, null=True)),
                ('mid_latitude', models.FloatField(blank=True, null=True)),
                ('mid_longitude', models.FloatField(blank=True, null=True)),
                ('year_recorded', models.IntegerField(blank=True, null=True)),
                ('geometry_json', models.JSONField(blank=True, null=True)),
                ('raw_attributes', models.JSONField(blank=True, default=dict)),
                ('data_quality_score', models.FloatField(default=0.0)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='routes.hpmslayercatalog')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='routes.hpmsinventorysource')),
            ],
            options={
                'verbose_name': 'Segmento HPMS',
                'verbose_name_plural': 'Segmentos HPMS',
                'ordering': ['state_name', 'route_number', 'segment_key'],
            },
        ),
        migrations.CreateModel(
            name='HPMSConditionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('iri', models.FloatField(blank=True, null=True)),
                ('iri_unit', models.CharField(default='in/mi', max_length=50)),
                ('roughness_class', models.CharField(blank=True, max_length=50)),
                ('surface_type', models.CharField(blank=True, max_length=100)),
                ('pavement_type', models.CharField(blank=True, max_length=100)),
                ('aadt', models.IntegerField(blank=True, null=True)),
                ('truck_aadt', models.IntegerField(blank=True, null=True)),
                ('lane_count', models.IntegerField(blank=True, null=True)),
                ('condition_score', models.FloatField(default=0.0)),
                ('data_quality_score', models.FloatField(default=0.0)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_snapshots', to='routes.hpmsroadsegment')),
            ],
            options={
                'verbose_name': 'Snapshot HPMS',
                'verbose_name_plural': 'Snapshots HPMS',
                'ordering': ['-year', 'segment__state_name'],
            },
        ),
        migrations.CreateModel(
            name='RouteSegmentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(default='heuristic', max_length=100)),
                ('overlap_ratio', models.FloatField(default=0.0)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('is_primary_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highway_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpms_matches', to='routes.highwayroute')),
                ('hpms_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_matches', to='routes.hpmsroadsegment')),
            ],
            options={
                'verbose_name': 'Match Ruta-HPMS',
                'verbose_name_plural': 'Matches Ruta-HPMS',
                'ordering': ['highway_route__route_name', '-is_primary_match'],
            },
        ),
        migrations.CreateModel(
            name='HPMSFieldCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_alias', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(blank=True, max_length=100)),
                ('is_nullable', models.BooleanField(default=True)),
                ('is_candidate_iri', models.BooleanField(default=False)),
                ('is_candidate_surface', models.BooleanField(default=False)),
                ('is_candidate_aadt', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='routes.hpmslayercatalog')),
            ],
            options={
                'verbose_name': 'Campo HPMS',
                'verbose_name_plural': 'Campos HPMS',
                'ordering': ['layer', 'field_name'],
                'unique_together': {('layer', 'field_name')},
            },
        ),
        migrations.AddIndex(
            model_name='hpmsroadsegment',
            index=models.Index(fields=['state_name', 'route_number'], name='routes_hpms_state_n_0b400b_idx'),
        ),
        migrations.AddIndex(
            model_name='hpmsroadsegment',
            index=models.Index(fields=['state_name', 'iri'], name='routes_hpms_state_n_54a80c_idx'),
        ),
        migrations.AddIndex(
            model_name='hpmsroadsegment',
            index=models.Index(fields=['is_nhs', 'is_interstate'], name='routes_hpms_is_nhs_099097_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hpmsconditionsnapshot',
            unique_together={('segment', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='routesegmentmatch',
            unique_together={('highway_route', 'hpms_segment')},
        ),
    ]
