# Generated by Django 5.1.3 on 2026-06-19 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TirePositionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, unique=True, verbose_name='Posición (Ej: FL-1)')),
                ('axle_type', models.CharField(choices=[('STEER', 'Steer'), ('DRIVE', 'Drive'), ('TRAILER', 'Trailer')], max_length=20, verbose_name='Tipo de Eje')),
                ('new_tread_depth', models.FloatField(help_text='En 32nds de pulgada', verbose_name='Profundidad Nueva')),
                ('warning_tread_depth', models.FloatField(verbose_name='Profundidad Advertencia')),
                ('critical_tread_depth', models.FloatField(verbose_name='Profundidad Crítica (Legal)')),
                ('target_pressure', models.FloatField(verbose_name='Presión Ideal (PSI)')),
                ('target_temperature', models.FloatField(verbose_name='Temperatura Ideal (°F)')),
                ('max_load', models.FloatField(verbose_name='Carga Máxima (lbs)')),
                ('base_lifecycle_miles', models.FloatField(verbose_name='Ciclo Base (millas)')),
                ('base_wear_rate', models.FloatField(verbose_name='Tasa de Desgaste Base (32nds / 1000 mi)')),
            ],
            options={
                'verbose_name': 'Configuración de Posición',
                'verbose_name_plural': 'Configuraciones de Posición',
            },
        ),
        migrations.CreateModel(
            name='TireMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=50, verbose_name='Tipo de Mantenimiento')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha/Hora')),
                ('mileage', models.FloatField(verbose_name='Millaje al Mantenimiento')),
                ('tread_before', models.FloatField(blank=True, null=True, verbose_name='Profundidad Antes (32nds)')),
                ('tread_after', models.FloatField(blank=True, null=True, verbose_name='Profundidad Después (32nds)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='devices.tiresensor')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TireReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pressure_psi', models.FloatField(verbose_name='Presión (PSI)')),
                ('temperature_f', models.FloatField(verbose_name='Temperatura (°F)')),
                ('vibration_g', models.FloatField(verbose_name='Vibración (G)')),
                ('estimated_tread_depth', models.FloatField(blank=True, null=True, verbose_name='Profundidad Estimada (32nds)')),
                ('rssi', models.FloatField(blank=True, null=True, verbose_name='Fuerza de Señal BT')),
                ('sensor_battery', models.FloatField(blank=True, null=True, verbose_name='Batería Sensor (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.tiresensor')),
            ],
            options={
                'verbose_name': 'Lectura de Llanta',
                'verbose_name_plural': 'Lecturas de Llantas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
