# Generated by Django 5.1.3 on 2026-06-20 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('TIRE_SHOP', 'Tienda de Llantas'), ('REST_STOP', 'Parada de Descanso'), ('RESTAURANT', 'Restaurante'), ('FUEL_STATION', 'Estación de Combustible'), ('ALT_FUEL', 'Combustible Alternativo'), ('RECYCLING_CENTER', 'Centro de Reciclaje'), ('WIM_STATION', 'Estación WIM'), ('HOTEL', 'Hotel'), ('MECHANIC', 'Mecánico')], max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('target_name', models.CharField(max_length=255)),
                ('target_address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('estimated_time_min', models.IntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generada'), ('SENT', 'Enviada al Conductor'), ('ACCEPTED', 'Aceptada'), ('REJECTED', 'Rechazada'), ('COMPLETED', 'Completada')], default='GENERATED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='alerts.alert')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='devices.truck')),
            ],
        ),
    ]
