# Generated by Django 5.1.3 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeFuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(choices=[('CNG', 'Compressed Natural Gas'), ('LNG', 'Liquefied Natural Gas'), ('ELEC', 'Electric'), ('H2', 'Hydrogen')], max_length=10)),
                ('is_hd_fuel', models.BooleanField(default=False, verbose_name='Heavy-Duty Ready')),
                ('access_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operators', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
