# Generated by Django 5.1.3 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity_tons', models.FloatField(blank=True, null=True)),
                ('recycling_type', models.CharField(max_length=100)),
                ('accepts_tires', models.BooleanField(default=False, verbose_name='Acepta Llantas Usadas')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
