# Generated by Django 5.1.3 on 2026-06-19 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, unique=True, verbose_name='Código de Estado (Ej: TX)')),
                ('state_name', models.CharField(max_length=100, verbose_name='Nombre del Estado')),
                ('federal_gross_limit', models.FloatField(default=80000.0, verbose_name='Límite Bruto Federal (lbs)')),
                ('state_gross_limit', models.FloatField(default=80000.0, verbose_name='Límite Bruto Estatal (lbs)')),
                ('single_axle_limit', models.FloatField(default=20000.0, verbose_name='Límite Eje Simple (lbs)')),
                ('tandem_axle_limit', models.FloatField(default=34000.0, verbose_name='Límite Eje Tándem (lbs)')),
                ('weight_wear_factor', models.FloatField(default=1.0, verbose_name='Factor Base de Desgaste por Peso')),
                ('permits_available', models.BooleanField(default=False, verbose_name='Permite Permisos de Exceso')),
            ],
            options={
                'verbose_name': 'Regulación de Peso',
                'verbose_name_plural': 'Regulaciones de Peso',
            },
        ),
        migrations.CreateModel(
            name='AxleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_number', models.IntegerField(verbose_name='Número de Eje (De frente a atrás)')),
                ('axle_type', models.CharField(choices=[('STEER', 'Eje de Dirección (Frontal)'), ('SINGLE', 'Eje Simple'), ('TANDEM', 'Eje Tándem'), ('TRIDEM', 'Eje Trídem')], max_length=10, verbose_name='Tipo de Eje')),
                ('position_ft', models.FloatField(verbose_name='Distancia desde el frente (Pies)')),
                ('tire_count', models.IntegerField(default=4, verbose_name='Número de Llantas en el Eje')),
                ('max_weight_capacity', models.FloatField(verbose_name='Capacidad Máxima Física (lbs)')),
                ('current_weight', models.FloatField(default=0.0, verbose_name='Peso Actual Estimado (lbs)')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axles', to='devices.truck')),
            ],
            options={
                'verbose_name': 'Configuración de Eje',
                'verbose_name_plural': 'Configuraciones de Ejes',
                'ordering': ['truck', 'axle_number'],
            },
        ),
        migrations.CreateModel(
            name='WeightInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación de la Inspección')),
                ('inspection_type', models.CharField(choices=[('WIM', 'Weigh-In-Motion (Dinámico)'), ('STATIC', 'Estación de Pesaje (Estático)'), ('ESTIMATED', 'Estimado por Sensores IoT')], max_length=15)),
                ('gross_weight', models.FloatField(verbose_name='Peso Bruto Registrado (lbs)')),
                ('axle_weights', models.JSONField(verbose_name='Pesos por Eje (JSON)')),
                ('is_overweight', models.BooleanField(default=False, verbose_name='¿Exceso de Peso?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_inspections', to='devices.truck')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weight_monitoring.weightregulation')),
            ],
            options={
                'verbose_name': 'Inspección de Peso',
                'verbose_name_plural': 'Inspecciones de Peso',
                'ordering': ['-timestamp'],
            },
        ),
    ]
