# Generated by Django 5.1.3 on 2026-06-20 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('TIRE_WEAR', 'Tire Wear Predictor'), ('TIRE_FAILURE', 'Tire Failure Predictor'), ('HOS_COMPLIANCE', 'HOS Compliance Predictor'), ('OVERWEIGHT_RISK', 'Overweight Risk Predictor'), ('DEMAND_FORECAST', 'Demand Forecaster'), ('LOCATION_OPTIMIZER', 'Optimal Location Recommender')], max_length=50)),
                ('prediction_data', models.JSONField(verbose_name='Resultados de la Predicción')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='devices.truck')),
            ],
        ),
    ]
