# Generated by Django 5.1.3 on 2026-06-19 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_weightenforcementstatistic'),
        ('devices', '0001_initial'),
        ('hos_monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.carriercompany')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente de Flota / Despachador',
                'verbose_name_plural': 'Gerentes de Flota / Despachadores',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_address', models.CharField(max_length=255, verbose_name='Origen')),
                ('destination_address', models.CharField(max_length=255, verbose_name='Destino')),
                ('scheduled_start', models.DateTimeField(verbose_name='Inicio Programado')),
                ('scheduled_end', models.DateTimeField(verbose_name='Fin Estimado')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio Real')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin Real')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_TRANSIT', 'En Tránsito'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('route_data', models.JSONField(blank=True, help_text='Coordenadas y waypoints de la ruta planeada.', null=True, verbose_name='Datos de Ruta (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.carriercompany', verbose_name='Empresa')),
                ('dispatcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_trips', to='fleet.fleetmanager', verbose_name='Despachador')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='hos_monitoring.driver', verbose_name='Conductor')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='devices.truck', verbose_name='Tractomula')),
            ],
            options={
                'verbose_name': 'Viaje / Despacho',
                'verbose_name_plural': 'Viajes / Despachos',
                'ordering': ['-scheduled_start'],
            },
        ),
    ]
